# fly.toml app configuration file generated for tryout-sample on 2024-03-11T13:18:32+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tryout-sample'
primary_region = 'sin'

[build]
  dockerfile = "Dockerfile"

[env]
  DB_HOST = 'artamananda-db.internal'
  DB_NAME = 'tryout_sample'
  DB_PASSWORD = 'oxmwhoFj1RZ9kTy'
  DB_POOL_IDLE_CONN = '5'
  DB_POOL_LIFE_TIME = '30000'
  DB_POOL_MAX_CONN = '10'
  DB_PORT = '5432'
  DB_USER = 'postgres'
  JWT_EXPIRE_MINUTES_COUNT = '60'
  JWT_SECRET_KEY = 'secret'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
