name: Telisik Web Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_WEB_PROJECT_ID }}
on:
  push:
    branches:
      - development
    paths:
      - web/**

jobs:
  deploy:
    name: Deploy WEB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - uses: culshaw/read-package-node-version-actions@v1
        with:
          path: "./web"
        id: package-json

      - name: Show version number
        run: echo "${{ steps.package-json.outputs.version }}"

      - name: Change to web directory
        run: cd web

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: "Add version on .env file"
        run: |
          echo "REACT_APP_VERSION_NAME=${{ steps.package-json.outputs.version }}" >> .vercel/.env.production.local

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
